import { z } from 'zod';

export const Currency = z.enum(['GBP', 'USD', 'EUR']);

export const CanvasItem = z.object({
  id: z.string(),
  text: z.string(),
});

export const AssociatedCost = z.object({
  id: z.string(),
  name: z.string(),
  amount: z.number().nonnegative(),
  productId: z.string(),
  projectId: z.string(),
});

export const ProductSales = z.object({
  volume: z.number().nonnegative(),
  period: z.enum(['monthly', 'daily']),
});

export const Product = z.object({
  id: z.string(),
  name: z.string(),
  price: z.number().nonnegative(),
  associatedCosts: z.array(AssociatedCost),
  projectId: z.string(),
  sales: ProductSales.optional(),
});

// Note: 'upfront' is intentionally not part of FixedCost.frequency in the unified model
export const FixedCost = z.object({
  id: z.string(),
  name: z.string(),
  amount: z.number().nonnegative(),
  frequency: z.enum(['monthly', 'annual']),
  category: z.string(),
  projectId: z.string(),
});

export const UpfrontCost = z.object({
  id: z.string(),
  name: z.string(),
  amount: z.number().nonnegative(),
  projectId: z.string(),
});

export const CostStructure = z.object({
  fixedRunningCosts: z.array(FixedCost),
  upfrontCosts: z.array(UpfrontCost).default([]),
});

export const RevenueStreams = z.object({
  products: z.array(Product),
});

export const Project = z.object({
  version: z.literal(2),
  id: z.string(),
  name: z.string(),
  // Optional short description of the business. Capped to ~2 paragraphs.
  description: z.string().max(600).optional(),
  // Tracks if the project was generated by AI and stores the original prompt
  aiGeneratedFromPrompt: z.string().optional(),
  currency: Currency,
  createdAt: z.string(),
  updatedAt: z.string(),
  costStructure: CostStructure,
  revenueStreams: RevenueStreams,
  partnerships: z.array(CanvasItem).default([]),
  activities: z.array(CanvasItem).default([]),
  valueProposition: z.array(CanvasItem).default([]),
  customerRelationships: z.array(CanvasItem).default([]),
  customerSegments: z.array(CanvasItem).default([]),
  resources: z.array(CanvasItem).default([]),
  channels: z.array(CanvasItem).default([]),
  sharedId: z.string().optional(),
});

export const ProjectsArray = z.array(Project);


